title: Sarvesh Ingle
description: Hi! I am a MSc Economics student at Indira Gandhi Institute of Development Research, Mumbai. My research interests broadly span <strong>theoretical and applied macroeconomics</strong> as well as <strong>applications of Machine Learning in Economics</strong>.
theme: jekyll-theme-minimal
