title: Sarvesh Ingle
description: Hi! I am a MSc Economics student at Indira Gandhi Institute of Development Research, Mumbai. My research interests broadly span \textbf{theoretical and applied macroeconomics} as well as \textbf{applications of Machine learning in Economics}. 
theme: jekyll-theme-minimal
